version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Masterrx8
    ports:
      - 5432:5432
volumes:
    pgdata:
